#!/bin/bash
# fresh_start.sh - Fresh start for Musli Scraper Service

set -e

echo "🚀 Fresh Start - Musli Scraper Service"
echo "======================================"

# 1. First fix the SQLC configuration
echo "📝 Creating proper sqlc.yaml configuration..."
cat > sqlc.yaml << 'EOF'
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/query/"
    schema: "db/migration/"
    gen:
      go:
        package: "db"
        out: "db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_db_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: true
        emit_empty_slices: true
        emit_exported_queries: true
        emit_result_struct_pointers: false
        emit_params_struct_pointers: false
        emit_methods_with_db_argument: false
        emit_enum_valid_method: true
        emit_all_enum_values: true
        overrides:
          - db_type: "job_status"
            go_type:
              type: "JobStatus"
          - column: "scraping_jobs.status"
            go_type:
              type: "JobStatus"
          - column: "*.created_at"
            go_type: "time.Time"
          - column: "*.updated_at"
            go_type: "time.Time"
          - column: "*.started_at"
            go_type: "time.Time"
          - column: "*.completed_at"
            go_type: 
              type: "*time.Time"
              pointer: true
          - column: "scraping_jobs.options"
            go_type: "encoding/json.RawMessage"
          - column: "scraping_jobs.metadata"
            go_type: "encoding/json.RawMessage"
          - column: "scraping_jobs.results"
            go_type: "encoding/json.RawMessage"
EOF

# 2. Start infrastructure
echo "🐳 Starting Docker infrastructure..."
docker-compose up -d postgres rabbitmq redis

echo "⏳ Waiting for services to be ready..."
sleep 15

# 3. Create database
echo "🗄️  Creating database..."
docker exec -it musli_postgres createdb --username=root --owner=root musli_scraper 2>/dev/null || true

# 4. Run migrations
echo "🗄️  Running migrations..."
make migrateup

# 5. Generate SQLC code
echo "🔧 Generating SQLC code..."
make sqlc

# 6. Create the JobStatus type file
echo "📝 Creating JobStatus type..."
mkdir -p db/sqlc
cat > db/sqlc/job_status_type.go << 'EOF'
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
)

type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusFailed     JobStatus = "failed"
	JobStatusCanceled   JobStatus = "canceled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", src, e)
	}
	return nil
}

func (e JobStatus) Value() (driver.Value, error) {
	return string(e), nil
}

func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusPending,
		JobStatusProcessing,
		JobStatusCompleted,
		JobStatusFailed,
		JobStatusCanceled:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}
EOF

# 7. Fix any remaining type issues in generated code
echo "📝 Fixing generated code types..."
# Fix interface{} to JobStatus in relevant files
find db/sqlc -name "*.go" -type f -exec sed -i 's/Status\s\+interface{}/Status JobStatus/g' {} \;

# 8. Build the service
echo "🏗️  Building the service..."
make build

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Fresh start complete!"
    echo ""
    echo "Service endpoints:"
    echo "  - API: http://localhost:8081"
    echo "  - Health: http://localhost:8081/health"
    echo "  - RabbitMQ UI: http://localhost:15672 (guest/guest)"
    echo ""
    echo "You can now run the service with:"
    echo "  ./bin/scraper-service"
    echo ""
    echo "Or run the test script:"
    echo "  ./test_scraper.sh"
else
    echo ""
    echo "❌ Build failed. Check the errors above."
fi