// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusFailed     JobStatus = "failed"
	JobStatusCanceled   JobStatus = "canceled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusPending,
		JobStatusProcessing,
		JobStatusCompleted,
		JobStatusFailed,
		JobStatusCanceled:
		return true
	}
	return false
}

func AllJobStatusValues() []JobStatus {
	return []JobStatus{
		JobStatusPending,
		JobStatusProcessing,
		JobStatusCompleted,
		JobStatusFailed,
		JobStatusCanceled,
	}
}

type JobMetrics struct {
	TotalJobs                int64          `db:"total_jobs" json:"total_jobs"`
	PendingJobs              int64          `db:"pending_jobs" json:"pending_jobs"`
	ProcessingJobs           int64          `db:"processing_jobs" json:"processing_jobs"`
	CompletedJobs            int64          `db:"completed_jobs" json:"completed_jobs"`
	FailedJobs               int64          `db:"failed_jobs" json:"failed_jobs"`
	CanceledJobs             int64          `db:"canceled_jobs" json:"canceled_jobs"`
	SuccessRate              pgtype.Numeric `db:"success_rate" json:"success_rate"`
	AvgProcessingTimeSeconds float64        `db:"avg_processing_time_seconds" json:"avg_processing_time_seconds"`
}

type ScrapingJobs struct {
	ID           string          `db:"id" json:"id"`
	Url          string          `db:"url" json:"url"`
	DatasourceID pgtype.Int4     `db:"datasource_id" json:"datasource_id"`
	CallbackUrl  pgtype.Text     `db:"callback_url" json:"callback_url"`
	Options      json.RawMessage `db:"options" json:"options"`
	Metadata     json.RawMessage `db:"metadata" json:"metadata"`
	Status       JobStatus       `db:"status" json:"status"`
	Progress     pgtype.Int4     `db:"progress" json:"progress"`
	StartedAt    time.Time       `db:"started_at" json:"started_at"`
	CompletedAt  **time.Time     `db:"completed_at" json:"completed_at"`
	Error        pgtype.Text     `db:"error" json:"error"`
	RetryCount   pgtype.Int4     `db:"retry_count" json:"retry_count"`
	Results      json.RawMessage `db:"results" json:"results"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at" json:"updated_at"`
}
