// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JobMetrics struct {
	TotalJobs                int64          `db:"total_jobs" json:"total_jobs"`
	PendingJobs              int64          `db:"pending_jobs" json:"pending_jobs"`
	ProcessingJobs           int64          `db:"processing_jobs" json:"processing_jobs"`
	CompletedJobs            int64          `db:"completed_jobs" json:"completed_jobs"`
	FailedJobs               int64          `db:"failed_jobs" json:"failed_jobs"`
	CanceledJobs             int64          `db:"canceled_jobs" json:"canceled_jobs"`
	SuccessRate              pgtype.Numeric `db:"success_rate" json:"success_rate"`
	AvgProcessingTimeSeconds float64        `db:"avg_processing_time_seconds" json:"avg_processing_time_seconds"`
}

type ScrapingJobs struct {
	ID           string           `db:"id" json:"id"`
	Url          string           `db:"url" json:"url"`
	DatasourceID pgtype.Int4      `db:"datasource_id" json:"datasource_id"`
	CallbackUrl  pgtype.Text      `db:"callback_url" json:"callback_url"`
	Options      []byte           `db:"options" json:"options"`
	Metadata     []byte           `db:"metadata" json:"metadata"`
	Status       JobStatus        `db:"status" json:"status"`
	Progress     pgtype.Int4      `db:"progress" json:"progress"`
	StartedAt    pgtype.Timestamp `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	Error        pgtype.Text      `db:"error" json:"error"`
	RetryCount   pgtype.Int4      `db:"retry_count" json:"retry_count"`
	Results      []byte           `db:"results" json:"results"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
