// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CancelJob(ctx context.Context, id string) (ScrapingJobs, error)
	CleanupOldJobs(ctx context.Context, createdAt time.Time) error
	CompleteJob(ctx context.Context, arg CompleteJobParams) (ScrapingJobs, error)
	CountJobsByStatus(ctx context.Context, status interface{}) (int64, error)
	CountTotalJobs(ctx context.Context) (int64, error)
	// db/query/scraping_jobs.sql
	// SQLC queries for scraping jobs management
	CreateScrapingJob(ctx context.Context, arg CreateScrapingJobParams) (ScrapingJobs, error)
	DeleteScrapingJob(ctx context.Context, id string) error
	FailJob(ctx context.Context, arg FailJobParams) (ScrapingJobs, error)
	GetActiveJobsCount(ctx context.Context) (int64, error)
	GetJobMetrics(ctx context.Context) (JobMetrics, error)
	GetJobsByDatasourceID(ctx context.Context, arg GetJobsByDatasourceIDParams) ([]ScrapingJobs, error)
	GetJobsByURLPattern(ctx context.Context, arg GetJobsByURLPatternParams) ([]ScrapingJobs, error)
	GetJobsForCleanup(ctx context.Context, arg GetJobsForCleanupParams) ([]GetJobsForCleanupRow, error)
	GetRecentJobs(ctx context.Context, arg GetRecentJobsParams) ([]ScrapingJobs, error)
	GetScrapingJob(ctx context.Context, id string) (ScrapingJobs, error)
	GetScrapingJobByURL(ctx context.Context, url string) (ScrapingJobs, error)
	GetStaleProcessingJobs(ctx context.Context, startedAt time.Time) ([]ScrapingJobs, error)
	ListPendingJobs(ctx context.Context, limit int32) ([]ScrapingJobs, error)
	ListProcessingJobs(ctx context.Context) ([]ScrapingJobs, error)
	ListScrapingJobs(ctx context.Context, arg ListScrapingJobsParams) ([]ScrapingJobs, error)
	ListScrapingJobsByStatus(ctx context.Context, arg ListScrapingJobsByStatusParams) ([]ScrapingJobs, error)
	RetryJob(ctx context.Context, arg RetryJobParams) (ScrapingJobs, error)
	StartJob(ctx context.Context, id string) (ScrapingJobs, error)
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (ScrapingJobs, error)
	UpdateJobResults(ctx context.Context, arg UpdateJobResultsParams) (ScrapingJobs, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (ScrapingJobs, error)
}

var _ Querier = (*Queries)(nil)
