// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scraping_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CancelJob = `-- name: CancelJob :one
UPDATE scraping_jobs 
SET status = 'canceled', completed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

func (q *Queries) CancelJob(ctx context.Context, id string) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, CancelJob, id)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CleanupOldJobs = `-- name: CleanupOldJobs :exec
DELETE FROM scraping_jobs 
WHERE created_at < $1 
AND status IN ('completed', 'failed', 'canceled')
`

func (q *Queries) CleanupOldJobs(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, CleanupOldJobs, createdAt)
	return err
}

const CompleteJob = `-- name: CompleteJob :one
UPDATE scraping_jobs 
SET status = 'completed', progress = 100, completed_at = CURRENT_TIMESTAMP, 
    results = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type CompleteJobParams struct {
	ID      string `db:"id" json:"id"`
	Results []byte `db:"results" json:"results"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, CompleteJob, arg.ID, arg.Results)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CountJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM scraping_jobs WHERE status = $1
`

func (q *Queries) CountJobsByStatus(ctx context.Context, status JobStatus) (int64, error) {
	row := q.db.QueryRow(ctx, CountJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTotalJobs = `-- name: CountTotalJobs :one
SELECT COUNT(*) FROM scraping_jobs
`

func (q *Queries) CountTotalJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountTotalJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateScrapingJob = `-- name: CreateScrapingJob :one

INSERT INTO scraping_jobs (
    id, url, datasource_id, callback_url, options, metadata, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type CreateScrapingJobParams struct {
	ID           string      `db:"id" json:"id"`
	Url          string      `db:"url" json:"url"`
	DatasourceID pgtype.Int4 `db:"datasource_id" json:"datasource_id"`
	CallbackUrl  pgtype.Text `db:"callback_url" json:"callback_url"`
	Options      []byte      `db:"options" json:"options"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
	Status       JobStatus   `db:"status" json:"status"`
}

// db/query/scraping_jobs.sql
// SQLC queries for scraping jobs management
func (q *Queries) CreateScrapingJob(ctx context.Context, arg CreateScrapingJobParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, CreateScrapingJob,
		arg.ID,
		arg.Url,
		arg.DatasourceID,
		arg.CallbackUrl,
		arg.Options,
		arg.Metadata,
		arg.Status,
	)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteScrapingJob = `-- name: DeleteScrapingJob :exec
DELETE FROM scraping_jobs WHERE id = $1
`

func (q *Queries) DeleteScrapingJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteScrapingJob, id)
	return err
}

const FailJob = `-- name: FailJob :one
UPDATE scraping_jobs 
SET status = 'failed', error = $2, completed_at = CURRENT_TIMESTAMP,
    retry_count = retry_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type FailJobParams struct {
	ID    string      `db:"id" json:"id"`
	Error pgtype.Text `db:"error" json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, FailJob, arg.ID, arg.Error)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveJobsCount = `-- name: GetActiveJobsCount :one
SELECT COUNT(*) FROM scraping_jobs 
WHERE status IN ('pending', 'processing')
`

func (q *Queries) GetActiveJobsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, GetActiveJobsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetJobMetrics = `-- name: GetJobMetrics :one
SELECT 
    total_jobs,
    pending_jobs,
    processing_jobs,
    completed_jobs,
    failed_jobs,
    canceled_jobs,
    success_rate,
    avg_processing_time_seconds
FROM job_metrics
`

func (q *Queries) GetJobMetrics(ctx context.Context) (JobMetrics, error) {
	row := q.db.QueryRow(ctx, GetJobMetrics)
	var i JobMetrics
	err := row.Scan(
		&i.TotalJobs,
		&i.PendingJobs,
		&i.ProcessingJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.CanceledJobs,
		&i.SuccessRate,
		&i.AvgProcessingTimeSeconds,
	)
	return i, err
}

const GetJobsByDatasourceID = `-- name: GetJobsByDatasourceID :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE datasource_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetJobsByDatasourceIDParams struct {
	DatasourceID pgtype.Int4 `db:"datasource_id" json:"datasource_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetJobsByDatasourceID(ctx context.Context, arg GetJobsByDatasourceIDParams) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, GetJobsByDatasourceID, arg.DatasourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetJobsByURLPattern = `-- name: GetJobsByURLPattern :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE url ILIKE $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetJobsByURLPatternParams struct {
	Url    string `db:"url" json:"url"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetJobsByURLPattern(ctx context.Context, arg GetJobsByURLPatternParams) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, GetJobsByURLPattern, arg.Url, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetJobsForCleanup = `-- name: GetJobsForCleanup :many
SELECT id, created_at, status FROM scraping_jobs 
WHERE created_at < $1 
AND status IN ('completed', 'failed', 'canceled')
LIMIT $2
`

type GetJobsForCleanupParams struct {
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Limit     int32            `db:"limit" json:"limit"`
}

type GetJobsForCleanupRow struct {
	ID        string           `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Status    JobStatus        `db:"status" json:"status"`
}

func (q *Queries) GetJobsForCleanup(ctx context.Context, arg GetJobsForCleanupParams) ([]GetJobsForCleanupRow, error) {
	rows, err := q.db.Query(ctx, GetJobsForCleanup, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForCleanupRow{}
	for rows.Next() {
		var i GetJobsForCleanupRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentJobs = `-- name: GetRecentJobs :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE created_at >= $1 
ORDER BY created_at DESC 
LIMIT $2
`

type GetRecentJobsParams struct {
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Limit     int32            `db:"limit" json:"limit"`
}

func (q *Queries) GetRecentJobs(ctx context.Context, arg GetRecentJobsParams) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, GetRecentJobs, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScrapingJob = `-- name: GetScrapingJob :one
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs WHERE id = $1
`

func (q *Queries) GetScrapingJob(ctx context.Context, id string) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, GetScrapingJob, id)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetScrapingJobByURL = `-- name: GetScrapingJobByURL :one
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs WHERE url = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetScrapingJobByURL(ctx context.Context, url string) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, GetScrapingJobByURL, url)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetStaleProcessingJobs = `-- name: GetStaleProcessingJobs :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE status = 'processing' 
AND started_at < $1
ORDER BY started_at ASC
`

func (q *Queries) GetStaleProcessingJobs(ctx context.Context, startedAt pgtype.Timestamp) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, GetStaleProcessingJobs, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingJobs = `-- name: ListPendingJobs :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE status = 'pending' 
ORDER BY created_at ASC 
LIMIT $1
`

func (q *Queries) ListPendingJobs(ctx context.Context, limit int32) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, ListPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProcessingJobs = `-- name: ListProcessingJobs :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE status = 'processing' 
ORDER BY started_at ASC
`

func (q *Queries) ListProcessingJobs(ctx context.Context) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, ListProcessingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScrapingJobs = `-- name: ListScrapingJobs :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
ORDER BY created_at DESC 
LIMIT $1 OFFSET $2
`

type ListScrapingJobsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListScrapingJobs(ctx context.Context, arg ListScrapingJobsParams) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, ListScrapingJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScrapingJobsByStatus = `-- name: ListScrapingJobsByStatus :many
SELECT id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at FROM scraping_jobs 
WHERE status = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListScrapingJobsByStatusParams struct {
	Status JobStatus `db:"status" json:"status"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListScrapingJobsByStatus(ctx context.Context, arg ListScrapingJobsByStatusParams) ([]ScrapingJobs, error) {
	rows, err := q.db.Query(ctx, ListScrapingJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJobs{}
	for rows.Next() {
		var i ScrapingJobs
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.DatasourceID,
			&i.CallbackUrl,
			&i.Options,
			&i.Metadata,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RetryCount,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RetryJob = `-- name: RetryJob :one
UPDATE scraping_jobs 
SET status = 'pending', error = NULL, progress = 0,
    retry_count = retry_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND retry_count < $2
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type RetryJobParams struct {
	ID         string      `db:"id" json:"id"`
	RetryCount pgtype.Int4 `db:"retry_count" json:"retry_count"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, RetryJob, arg.ID, arg.RetryCount)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const StartJob = `-- name: StartJob :one
UPDATE scraping_jobs 
SET status = 'processing', started_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

func (q *Queries) StartJob(ctx context.Context, id string) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, StartJob, id)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateJobProgress = `-- name: UpdateJobProgress :one
UPDATE scraping_jobs 
SET progress = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type UpdateJobProgressParams struct {
	ID       string      `db:"id" json:"id"`
	Progress pgtype.Int4 `db:"progress" json:"progress"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, UpdateJobProgress, arg.ID, arg.Progress)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateJobResults = `-- name: UpdateJobResults :one
UPDATE scraping_jobs 
SET results = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type UpdateJobResultsParams struct {
	ID      string `db:"id" json:"id"`
	Results []byte `db:"results" json:"results"`
}

func (q *Queries) UpdateJobResults(ctx context.Context, arg UpdateJobResultsParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, UpdateJobResults, arg.ID, arg.Results)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateJobStatus = `-- name: UpdateJobStatus :one
UPDATE scraping_jobs 
SET status = $2, progress = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
RETURNING id, url, datasource_id, callback_url, options, metadata, status, progress, started_at, completed_at, error, retry_count, results, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID       string      `db:"id" json:"id"`
	Status   JobStatus   `db:"status" json:"status"`
	Progress pgtype.Int4 `db:"progress" json:"progress"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (ScrapingJobs, error) {
	row := q.db.QueryRow(ctx, UpdateJobStatus, arg.ID, arg.Status, arg.Progress)
	var i ScrapingJobs
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DatasourceID,
		&i.CallbackUrl,
		&i.Options,
		&i.Metadata,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RetryCount,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
